### PR TITLE
v0.0.20

### LINKED ISSUE #115: [Bug] krux-installer not starting on Fedora 41 with Gnome (Wayland)
I installed krux-installer (version v0.0.20-beta) using the rpm package on a Fedora 41 system (with Gnome and Wayland), but when I try to open the app it quits almost instantly and it gives this error when I launch it from a terminal:
```
...
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [KruxInstallerApp          ] Adding resources from /tmp/_MEIYUGphJ
[INFO   ] [KruxInstallerApp          ] Registering assets path=/tmp/_MEIYUGphJ/assets
[INFO   ] [KruxInstallerApp          ] <kivy.config.ConfigParser object at 0x7fafea58aab0>.lang=en_US.UTF-8
[INFO   ] [GL          ] NPOT texture support is available
 Traceback (most recent call last):
   File "krux-installer.py", line 29, in <module>
   File "kivy/app.py", line 955, in run
   File "kivy/app.py", line 925, in _run_prepare
   File "src/app/__init__.py", line 77, in build
     ----------------------
                            
   File "src/app/screens/ask_permission_dialout_screen.py", line 52, in __init__
   File "src/app/screens/ask_permission_dialout_screen.py", line 153, in detect_usermod_bin
   File "src/app/screens/base_screen.py", line 394, in redirect_exception
 AttributeError: 'NoneType' object has no attribute 'get_screen'
[PYI-35402:ERROR] Failed to execute script 'krux-installer' due to unhandled exception!
```
(I already restarted the system after installing the package)

While version v0.0.20-alpha-3 is working.

### LINKED ISSUE #116: [Enhancement] Add "disconnect/reconnect" message after wipe screen
#### The problem

In some systems, specially Win32, after wipe procedure is done, the OS stop to recognize a plugged device. If user try to flash the device without disconnect and reconnect device, the flash will fail.

### Solution

Add a simple message like "disconnect and reconnect your device before flash" on WipeScreen

### LINKED ISSUE #117: [Bug]  Adding better error screen when flash/wipe fails
When flash wipe/fails, redirect the errors to ErrorScreen

### PR DESCRIPTION
**Pull request by qlrd**
Minor changes on this PR:

* Coveraged code to about ~99%;
* fixes error messages when something go wrong during flashes;

### CODE REVIEW

**Review by odudex — APPROVED** [review]

**Comment by qlrd** [comment]
Fix #115 as mentioned by @ciori

**Review by odudex — APPROVED** [review]

**Comment by qlrd** [comment]
Fix #116.

@PMK, @theBillLee, @BitCoisas can you review the nl_NL.json, zh_CN.json and jp_JA.json translations for the new entry (`"disconnect and reconnect device before flash again"`)?

```json
"wipe_screen": {
    "PLEASE DO NOT UNPLUG YOUR DEVICE": "PLEASE DO NOT UNPLUG YOUR DEVICE",
    "DONE": "DONE",
    "Back": "Back",
    "Quit": "Quit",
    "disconnect and reconnect device before flash again": "disconnect and reconnect device before flash again"
  },
```

**Comment by PMK** [comment]
> Fix #116.
> 
> @PMK, @theBillLee, @BitCoisas can you review the nl_NL.json, zh_CN.json and jp_JA.json translations for the new entry (`"disconnect and reconnect device before flash again"`)?
> 
> ```json
> "wipe_screen": {
>     "PLEASE DO NOT UNPLUG YOUR DEVICE": "PLEASE DO NOT UNPLUG YOUR DEVICE",
>     "DONE": "DONE",
>     "Back": "Back",
>     "Quit": "Quit",
>     "disconnect and reconnect device before flash again": "disconnect and reconnect device before flash again"
>   },
> ```

ACK

**Review by odudex — APPROVED** [review]

**Comment by bitcoisas** [comment]
> Fix #116.
> 
> @PMK, @theBillLee, @BitCoisas can you review the nl_NL.json, zh_CN.json and jp_JA.json translations for the new entry (`"disconnect and reconnect device before flash again"`)?
> 
> ```json
> "wipe_screen": {
>     "PLEASE DO NOT UNPLUG YOUR DEVICE": "PLEASE DO NOT UNPLUG YOUR DEVICE",
>     "DONE": "DONE",
>     "Back": "Back",
>     "Quit": "Quit",
>     "disconnect and reconnect device before flash again": "disconnect and reconnect device before flash again"
>   },
> ```

ACK. The phrase is well-translated and understandable. However, using '再フラッシュ' instead of '再度フラッシュ' makes it sound more natural in technical contexts. Thxx!!!

**Review by bitcoisas — APPROVED** [review]
Nice! Arigatou!!!

**Pull request merged**
